server:
  port: 8761

spring:
  application:
    name: eurekaserver1

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false